apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: sample-spark-app
  namespace: spark-operator 
spec:
  type: Java
  mode: cluster
  image: "albertoclaritdocker/spark-operator-sample:1.0.0-009"
  imagePullPolicy: Always
  mainClass: org.example.App
  mainApplicationFile: "local:///opt/spark/work-dir/running/spark-app.jar"
  sparkVersion: "3.5.5"
  restartPolicy:
    type: Never
  sparkConf:
    "fs.http.impl": "org.apache.hadoop.fs.http.HttpFileSystem"
  deps:
    jars:
      - "local:///opt/spark/work-dir/jars/accessors-smart-2.4.7.jar"
      - "local:///opt/spark/work-dir/jars/animal-sniffer-annotations-1.17.jar"
      - "local:///opt/spark/work-dir/jars/aopalliance-1.0.jar"
      - "local:///opt/spark/work-dir/jars/asm-9.1.jar"
      - "local:///opt/spark/work-dir/jars/audience-annotations-0.5.0.jar"
      - "local:///opt/spark/work-dir/jars/avro-1.7.7.jar"
      - "local:///opt/spark/work-dir/jars/aws-java-sdk-bundle-1.12.262.jar"
      - "local:///opt/spark/work-dir/jars/checker-qual-2.5.2.jar"
      - "local:///opt/spark/work-dir/jars/commons-beanutils-1.9.4.jar"
      - "local:///opt/spark/work-dir/jars/commons-cli-1.2.jar"
      - "local:///opt/spark/work-dir/jars/commons-codec-1.15.jar"
      - "local:///opt/spark/work-dir/jars/commons-collections-3.2.2.jar"
      - "local:///opt/spark/work-dir/jars/commons-compress-1.21.jar"
      - "local:///opt/spark/work-dir/jars/commons-configuration2-2.1.1.jar"
      - "local:///opt/spark/work-dir/jars/commons-io-2.8.0.jar"
      - "local:///opt/spark/work-dir/jars/commons-lang3-3.12.0.jar"
      - "local:///opt/spark/work-dir/jars/commons-logging-1.2.jar"
      - "local:///opt/spark/work-dir/jars/commons-math3-3.1.1.jar"
      - "local:///opt/spark/work-dir/jars/commons-net-3.6.jar"
      - "local:///opt/spark/work-dir/jars/commons-text-1.4.jar"
      - "local:///opt/spark/work-dir/jars/curator-client-4.2.0.jar"
      - "local:///opt/spark/work-dir/jars/curator-framework-4.2.0.jar"
      - "local:///opt/spark/work-dir/jars/curator-recipes-4.2.0.jar"
      - "local:///opt/spark/work-dir/jars/dnsjava-2.1.7.jar"
      - "local:///opt/spark/work-dir/jars/error_prone_annotations-2.2.0.jar"
      - "local:///opt/spark/work-dir/jars/failureaccess-1.0.jar"
      - "local:///opt/spark/work-dir/jars/gson-2.8.9.jar"
      - "local:///opt/spark/work-dir/jars/guava-27.0-jre.jar"
      - "local:///opt/spark/work-dir/jars/guice-4.0.jar"
      - "local:///opt/spark/work-dir/jars/guice-servlet-4.0.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-annotations-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-auth-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-aws-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-client-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-common-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-hdfs-client-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-mapreduce-client-common-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-mapreduce-client-core-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-mapreduce-client-jobclient-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-shaded-guava-1.1.1.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-shaded-protobuf_3_7-1.1.1.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-yarn-api-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-yarn-client-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-yarn-common-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/httpclient-4.5.13.jar"
      - "local:///opt/spark/work-dir/jars/httpcore-4.4.13.jar"
      - "local:///opt/spark/work-dir/jars/j2objc-annotations-1.1.jar"
      - "local:///opt/spark/work-dir/jars/jackson-annotations-2.12.7.jar"
      - "local:///opt/spark/work-dir/jars/jackson-core-2.12.7.jar"
      - "local:///opt/spark/work-dir/jars/jackson-core-asl-1.9.13.jar"
      - "local:///opt/spark/work-dir/jars/jackson-databind-2.12.7.jar"
      - "local:///opt/spark/work-dir/jars/jackson-jaxrs-1.9.2.jar"
      - "local:///opt/spark/work-dir/jars/jackson-jaxrs-base-2.12.7.jar"
      - "local:///opt/spark/work-dir/jars/jackson-jaxrs-json-provider-2.12.7.jar"
      - "local:///opt/spark/work-dir/jars/jackson-mapper-asl-1.9.13.jar"
      - "local:///opt/spark/work-dir/jars/jackson-module-jaxb-annotations-2.12.7.jar"
      - "local:///opt/spark/work-dir/jars/jackson-xc-1.9.2.jar"
      - "local:///opt/spark/work-dir/jars/jakarta.activation-api-1.2.1.jar"
      - "local:///opt/spark/work-dir/jars/jakarta.xml.bind-api-2.3.2.jar"
      - "local:///opt/spark/work-dir/jars/javax.inject-1.jar"
      - "local:///opt/spark/work-dir/jars/javax.servlet-api-3.1.0.jar"
      - "local:///opt/spark/work-dir/jars/jaxb-api-2.2.11.jar"
      - "local:///opt/spark/work-dir/jars/jaxb-impl-2.2.3-1.jar"
      - "local:///opt/spark/work-dir/jars/jcip-annotations-1.0-1.jar"
      - "local:///opt/spark/work-dir/jars/jersey-client-1.19.jar"
      - "local:///opt/spark/work-dir/jars/jersey-core-1.19.jar"
      - "local:///opt/spark/work-dir/jars/jersey-guice-1.19.jar"
      - "local:///opt/spark/work-dir/jars/jersey-json-1.19.jar"
      - "local:///opt/spark/work-dir/jars/jersey-server-1.19.jar"
      - "local:///opt/spark/work-dir/jars/jersey-servlet-1.19.jar"
      - "local:///opt/spark/work-dir/jars/jettison-1.1.jar"
      - "local:///opt/spark/work-dir/jars/jetty-client-9.4.43.v20210629.jar"
      - "local:///opt/spark/work-dir/jars/jetty-http-9.4.43.v20210629.jar"
      - "local:///opt/spark/work-dir/jars/jetty-io-9.4.43.v20210629.jar"
      - "local:///opt/spark/work-dir/jars/jetty-security-9.4.43.v20210629.jar"
      - "local:///opt/spark/work-dir/jars/jetty-server-9.4.43.v20210629.jar"
      - "local:///opt/spark/work-dir/jars/jetty-servlet-9.4.43.v20210629.jar"
      - "local:///opt/spark/work-dir/jars/jetty-util-9.4.43.v20210629.jar"
      - "local:///opt/spark/work-dir/jars/jetty-util-ajax-9.4.43.v20210629.jar"
      - "local:///opt/spark/work-dir/jars/jetty-webapp-9.4.43.v20210629.jar"
      - "local:///opt/spark/work-dir/jars/jetty-xml-9.4.43.v20210629.jar"
      - "local:///opt/spark/work-dir/jars/jline-3.9.0.jar"
      - "local:///opt/spark/work-dir/jars/jsch-0.1.55.jar"
      - "local:///opt/spark/work-dir/jars/json-smart-2.4.7.jar"
      - "local:///opt/spark/work-dir/jars/jsp-api-2.1.jar"
      - "local:///opt/spark/work-dir/jars/jsr305-3.0.2.jar"
      - "local:///opt/spark/work-dir/jars/jsr311-api-1.1.1.jar"
      - "local:///opt/spark/work-dir/jars/kerb-admin-1.0.1.jar"
      - "local:///opt/spark/work-dir/jars/kerb-client-1.0.1.jar"
      - "local:///opt/spark/work-dir/jars/kerb-common-1.0.1.jar"
      - "local:///opt/spark/work-dir/jars/kerb-core-1.0.1.jar"
      - "local:///opt/spark/work-dir/jars/kerb-crypto-1.0.1.jar"
      - "local:///opt/spark/work-dir/jars/kerb-identity-1.0.1.jar"
      - "local:///opt/spark/work-dir/jars/kerb-server-1.0.1.jar"
      - "local:///opt/spark/work-dir/jars/kerb-simplekdc-1.0.1.jar"
      - "local:///opt/spark/work-dir/jars/kerb-util-1.0.1.jar"
      - "local:///opt/spark/work-dir/jars/kerby-asn1-1.0.1.jar"
      - "local:///opt/spark/work-dir/jars/kerby-config-1.0.1.jar"
      - "local:///opt/spark/work-dir/jars/kerby-pkix-1.0.1.jar"
      - "local:///opt/spark/work-dir/jars/kerby-util-1.0.1.jar"
      - "local:///opt/spark/work-dir/jars/kerby-xdr-1.0.1.jar"
      - "local:///opt/spark/work-dir/jars/kotlin-stdlib-1.4.10.jar"
      - "local:///opt/spark/work-dir/jars/kotlin-stdlib-common-1.4.10.jar"
      - "local:///opt/spark/work-dir/jars/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar"
      - "local:///opt/spark/work-dir/jars/log4j-1.2.17.jar"
      - "local:///opt/spark/work-dir/jars/netty-3.10.6.Final.jar"
      - "local:///opt/spark/work-dir/jars/netty-buffer-4.1.42.Final.jar"
      - "local:///opt/spark/work-dir/jars/netty-codec-4.1.42.Final.jar"
      - "local:///opt/spark/work-dir/jars/netty-common-4.1.42.Final.jar"
      - "local:///opt/spark/work-dir/jars/netty-handler-4.1.42.Final.jar"
      - "local:///opt/spark/work-dir/jars/netty-resolver-4.1.42.Final.jar"
      - "local:///opt/spark/work-dir/jars/netty-transport-4.1.42.Final.jar"
      - "local:///opt/spark/work-dir/jars/netty-transport-native-epoll-4.1.42.Final.jar"
      - "local:///opt/spark/work-dir/jars/netty-transport-native-unix-common-4.1.42.Final.jar"
      - "local:///opt/spark/work-dir/jars/nimbus-jose-jwt-9.8.1.jar"
      - "local:///opt/spark/work-dir/jars/okhttp-4.9.3.jar"
      - "local:///opt/spark/work-dir/jars/okio-jvm-2.8.0.jar"
      - "local:///opt/spark/work-dir/jars/paranamer-2.3.jar"
      - "local:///opt/spark/work-dir/jars/protobuf-java-2.5.0.jar"
      - "local:///opt/spark/work-dir/jars/re2j-1.1.jar"
      - "local:///opt/spark/work-dir/jars/reload4j-1.2.22.jar"
      - "local:///opt/spark/work-dir/jars/slf4j-api-1.7.36.jar"
      - "local:///opt/spark/work-dir/jars/slf4j-log4j12-1.7.25.jar"
      - "local:///opt/spark/work-dir/jars/slf4j-reload4j-1.7.36.jar"
      - "local:///opt/spark/work-dir/jars/snappy-java-1.1.8.2.jar"
      - "local:///opt/spark/work-dir/jars/stax2-api-4.2.1.jar"
      - "local:///opt/spark/work-dir/jars/token-provider-1.0.1.jar"
      - "local:///opt/spark/work-dir/jars/websocket-api-9.4.43.v20210629.jar"
      - "local:///opt/spark/work-dir/jars/websocket-client-9.4.43.v20210629.jar"
      - "local:///opt/spark/work-dir/jars/websocket-common-9.4.43.v20210629.jar"
      - "local:///opt/spark/work-dir/jars/wildfly-openssl-1.0.7.Final.jar"
      - "local:///opt/spark/work-dir/jars/woodstox-core-5.3.0.jar"
      - "local:///opt/spark/work-dir/jars/zookeeper-3.5.6.jar"
      - "local:///opt/spark/work-dir/jars/zookeeper-jute-3.5.6.jar"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.5
    serviceAccount: spark

  executor:
    cores: 1
    instances: 3
    memory: "512m"
    labels:
      version: 3.5.5
