apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: sample-spark-app
  namespace: spark-operator 
spec:
  type: Java
  mode: cluster
  image: "albertoclaritdocker/spark-operator-sample:0.0.14"
  imagePullPolicy: Always
  mainClass: org.example.App
  mainApplicationFile: "local:///opt/spark/work-dir/running/spark-app.jar"
  sparkVersion: "3.5.5"
  restartPolicy:
    type: Never
  sparkConf:
    "fs.http.impl": "org.apache.hadoop.fs.http.HttpFileSystem"
  deps:
    jars:
      - "local:///opt/spark/work-dir/jars/accessors-smart-2.4.7.jar"
      - "local:///opt/spark/work-dir/jars/activation-1.1.jar"
      - "local:///opt/spark/work-dir/jars/animal-sniffer-annotations-1.17.jar"
      - "local:///opt/spark/work-dir/jars/aopalliance-1.0.jar"
      - "local:///opt/spark/work-dir/jars/asm-9.1.jar"
      - "local:///opt/spark/work-dir/jars/audience-annotations-0.5.0.jar"
      - "local:///opt/spark/work-dir/jars/avro-1.7.7.jar"
      - "local:///opt/spark/work-dir/jars/aws-java-sdk-bundle-1.12.262.jar"
      - "local:///opt/spark/work-dir/jars/checker-qual-2.5.2.jar"
      - "local:///opt/spark/work-dir/jars/commons-beanutils-1.9.4.jar"
      - "local:///opt/spark/work-dir/jars/commons-cli-1.2.jar"
      - "local:///opt/spark/work-dir/jars/commons-codec-1.15.jar"
      - "local:///opt/spark/work-dir/jars/commons-collections-3.2.2.jar"
      - "local:///opt/spark/work-dir/jars/commons-compress-1.21.jar"
      - "local:///opt/spark/work-dir/jars/commons-configuration2-2.1.1.jar"
      - "local:///opt/spark/work-dir/jars/commons-daemon-1.0.13.jar"
      - "local:///opt/spark/work-dir/jars/commons-io-2.8.0.jar"
      - "local:///opt/spark/work-dir/jars/commons-lang3-3.12.0.jar"
      - "local:///opt/spark/work-dir/jars/commons-logging-1.2.jar"
      - "local:///opt/spark/work-dir/jars/commons-math3-3.1.1.jar"
      - "local:///opt/spark/work-dir/jars/commons-net-3.6.jar"
      - "local:///opt/spark/work-dir/jars/commons-text-1.4.jar"
      - "local:///opt/spark/work-dir/jars/curator-client-4.2.0.jar"
      - "local:///opt/spark/work-dir/jars/curator-framework-4.2.0.jar"
      - "local:///opt/spark/work-dir/jars/curator-recipes-4.2.0.jar"
      - "local:///opt/spark/work-dir/jars/dnsjava-2.1.7.jar"
      - "local:///opt/spark/work-dir/jars/error_prone_annotations-2.2.0.jar"
      - "local:///opt/spark/work-dir/jars/failureaccess-1.0.jar"
      - "local:///opt/spark/work-dir/jars/gson-2.8.9.jar"
      - "local:///opt/spark/work-dir/jars/guava-27.0-jre.jar"
      - "local:///opt/spark/work-dir/jars/guice-4.0.jar"
      - "local:///opt/spark/work-dir/jars/guice-servlet-4.0.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-annotations-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-auth-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-aws-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-client-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-common-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-hdfs-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-hdfs-client-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-mapreduce-client-common-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-mapreduce-client-core-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-mapreduce-client-jobclient-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-shaded-guava-1.1.1.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-shaded-protobuf_3_7-1.1.1.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-yarn-api-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-yarn-client-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/hadoop-yarn-common-3.3.4.jar"
      - "local:///opt/spark/work-dir/jars/httpclient-4.5.13.jar"
      - "local:///opt/spark/work-dir/jars/httpcore-4.4.13.jar"
      - "local:///opt/spark/work-dir/jars/j2objc-annotations-1.1.jar"
      - "local:///opt/spark/work-dir/jars/jackson-annotations-2.12.7.jar"
      - "local:///opt/spark/work-dir/jars/jackson-core-2.12.7.jar"
      - "local:///opt/spark/work-dir/jars/jackson-core-asl-1.9.13.jar"
      - "local:///opt/spark/work-dir/jars/jackson-databind-2.12.7.jar"
      - "local:///opt/spark/work-dir/jars/jackson-jaxrs-1.9.2.jar"
      - "local:///opt/spark/work-dir/jars/jackson-mapper-asl-1.9.13.jar"
      - "local:///opt/spark/work-dir/jars/jackson-xc-1.9.2.jar"
      - "local:///opt/spark/work-dir/jars/jakarta.activation-api-1.2.1.jar"
      - "local:///opt/spark/work-dir/jars/javax.servlet-api-3.1.0.jar"
      - "local:///opt/spark/work-dir/jars/jaxb-api-2.2.2.jar"
      - "local:///opt/spark/work-dir/jars/jaxb-impl-2.2.3-1.jar"
      - "local:///opt/spark/work-dir/jars/jcip-annotations-1.0-1.jar"
      - "local:///opt/spark/work-dir/jars/jersey-core-1.19.jar"
      - "local:///opt/spark/work-dir/jars/jersey-json-1.19.jar"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.5
    serviceAccount: spark

  executor:
    cores: 1
    instances: 15
    memory: "512m"
    labels:
      version: 3.5.5
